---

root: '/var/www/'

#Live sites go in the 'sites' dict. Remove this dict if it is not going to be used
sites:
 - { repo: 'git@github.com:carvey/EagleTrack.git', name: 'eagletrack', domain: 'charlesarvey.com' }

#sites that need to be removed go in the 'disabled' dict. Remove this dict when it is not being used
#EX:
#disabled:
# - { repo: 'git@github.com:username/project.git', name: 'my_project', domain: 'mysite.com' }

disabled:
  - { repo: 'git@github.com:carvey/blogger.git', name: 'blog', domain: 'charlesarvey.com'}
  - { repo: 'git@github.com:carvey/savoysterhouse.git', name: 'savoysterhouse', domain: 'savannahsoysterhouse.com'}